### ISSUE TITLE
gl_sdl2.c still references gl_sdl2.h even though it is deleted

### ISSUE THREAD

**Issue by jspenguin** [q2vr/quake2vr#23]
Pretty simple fix; I already fixed it in my fork, but I also brought in all the changes to vrgamex86.so that haven't been incorporated into the base yet

**Comment by dghost** [comment]
Cool. I thought I fixed this but must have missed it.

**Comment by dghost** [comment]
Also - I'm currently off working on the `osx` branch, and have made a number of changes (updating CMake + dependencies, etc) that may break your fork. The last remaining tasks before I merged it master was to fix building under Windows and make sure it still builds under Linux.

The good news is that if it does build under Linux it should bring support for OpenAL and the mission packs along with it.

**Comment by dghost** [comment]
Fixed as part of merging in the OS X support.
