### ISSUE TITLE
HDM not detected

### ISSUE THREAD

**Issue by upperking** [q2vr/quake2vr#31]
IS there still support for this?
I would love to see it updated since 2016 is the VR movement and this is the only software that support quake2 VR.

**Comment by badjano** [comment]
bump, CV1 here not working, VR: Error - no HMD attached

**Comment by dghost** [comment]
Hey, sorry for taking so long to get back to you guys on this. I've been dealing with health issues recently and haven't been able to work on this, but hopefully I'll be able to soon.

Sorry for making you guys wait!

**Comment by badjano** [comment]
Don't worry dude, if you fix it, it will definitely be worth the wait :) thank you for doing this for us!

**Comment by badjano** [comment]
and get well soon!

**Comment by Flunx** [comment]
bump!
Hope you're doing better dghost. Any hope of an update?

**Comment by GibStorm** [comment]
Really wish this game would work with the CV1. It would be the most awesome thing ever.

Sorry to hear you're having health problems. Hope you get well soon!

**Comment by badjano** [comment]
@dghost any news? Hope you're all right! I'm a developer myself, if you want I can help, can you point me in the right direction here? Thanks!

**Comment by TheSpazman** [comment]
Any hope of an update for CV1 to this? Right now, I can't get VR enabled at all.

**Comment by mscoder610** [comment]
There's now CV1 + partial Touch support in v2.0.0a.

Binaries are here: https://github.com/q2vr/quake2vr/releases/tag/v2.0.0a
Other downloads (shareware pack, binaries + HD textures) are here: http://www.malcolm-s.net/q2vr/
