### ISSUE TITLE
Rift CV1 + Touch support ?

### ISSUE THREAD

**Issue by motorsep** [q2vr/quake2vr#33]
Any chance to get CV1 + Touch support with teleportation locomotion as seen in Robo Recall?

**Comment by mscoder610** [comment]
There's now CV1 + partial Touch support in v2.0.0a.

Binaries are here: https://github.com/q2vr/quake2vr/releases/tag/v2.0.0a
Other downloads (shareware pack, binaries + HD textures) are here: http://www.malcolm-s.net/q2vr/

Currently there's no support for teleportation, but I created a separate issue for that (tagged as an Enhancement) for tracking purposes: https://github.com/q2vr/quake2vr/issues/34
